/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wikim' at '15. 3. 17 오후 8:56' with Gradle 2.2.1
 *
 * @author wikim, @date 15. 3. 17 오후 8:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
